# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated environment DSL (.py)
"""

from calm.dsl.builtins import *

# Secret Variables
BP_CRED_test_creds_PASSWORD = read_local_file("BP_CRED_test_creds_PASSWORD")
BP_CRED_test_creds = basic_cred(
    "admin",
    BP_CRED_test_creds_PASSWORD,
    name="test_creds",
    type="PASSWORD",
)


class vmcalm_array_indexcalm_timeResources(AhvVmResources):

    memory = 1
    vCPUs = 1
    cores_per_vCPU = 1
    disks = [
        AhvVmDisk.Disk.Scsi.cloneFromImageService("Centos7HadoopMaster", bootable=True)
    ]


class vmcalm_array_indexcalm_time(AhvVm):

    name = "vm-@@{calm_array_index}@@-@@{calm_time}@@"
    resources = vmcalm_array_indexcalm_timeResources
    cluster = Ref.Cluster(name="auto_cluster_prod_4faf4699cdea")


class Untitled(Substrate):

    account = Ref.Account("NTNX_LOCAL_AZ")
    os_type = "Linux"
    provider_type = "AHV_VM"
    provider_spec = vmcalm_array_indexcalm_time

    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=True,
        retries="5",
        connection_port=22,
        delay_secs="0",
    )


class ENV_test_decompile_env(Environment):
    substrates = [Untitled]
    credentials = [BP_CRED_test_creds]

    providers = [
        Provider.Ntnx(
            account=Ref.Account("NTNX_LOCAL_AZ"),
            subnets=[
                Ref.Subnet(
                    name="vlan.154",
                    cluster="auto_cluster_prod_4faf4699cdea",
                )
            ],
        ),
    ]
