# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from calm.dsl.builtins import CalmTask as CalmVarTask
from calm.dsl.builtins import *  # no_qa
from calm.dsl.runbooks import CalmEndpoint as Endpoint

# Secret Variables

BP_CRED_cred_PASSWORD = read_local_file("BP_CRED_cred_PASSWORD")

# Credentials
BP_CRED_cred = basic_cred(
    "admin",
    BP_CRED_cred_PASSWORD,
    name="cred",
    type="PASSWORD",
    default=True,
)


class Service1(Service):

    pass


class vmcalm_timeglobalgv_varResources(AhvVmResources):

    memory = 1
    vCPUs = 1
    cores_per_vCPU = 1
    disks = [
        AhvVmDisk.Disk.Scsi.cloneFromImageService("Centos7HadoopMaster", bootable=True)
    ]
    nics = [
        AhvVmNic.NormalNic.ingress("vlan1211", cluster="auto_cluster_prod_e9093c2aff01")
    ]

    power_state = "ON"
    boot_type = "LEGACY"


class vmcalm_timeglobalgv_var(AhvVm):

    name = "vm-@@{calm_time}@@-@@{global.gv_var}@@"
    resources = vmcalm_timeglobalgv_varResources
    cluster = Ref.Cluster(name="auto_cluster_prod_e9093c2aff01")


class VM1(Substrate):

    account = Ref.Account("NTNX_LOCAL_AZ")
    os_type = "Linux"
    provider_type = "AHV_VM"
    provider_spec = vmcalm_timeglobalgv_var

    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=True,
        retries="5",
        connection_port=22,
        address="@@{platform.status.resources.nic_list[0].ip_endpoint_list[0].ip}@@",
        delay_secs="60",
        credential=ref(BP_CRED_cred),
    )


class Package1(Package):

    services = [ref(Service1)]


class deployment_d07d576f(Deployment):

    min_replicas = "1"
    max_replicas = "1"
    default_replicas = "1"

    packages = [ref(Package1)]
    substrate = ref(VM1)


class Default(Profile):

    environments = [Ref.Environment(name="test_envd7a614a6bd6f")]
    deployments = [deployment_d07d576f]

    app_var = CalmVariable.Simple(
        "one",
        label="",
        regex="^.*$",
        validate_regex=False,
        is_mandatory=False,
        is_hidden=False,
        runtime=False,
        description="",
    )

    @action
    def CustomAction1():

        CalmTask.Exec.escript.py3(
            name="Task1",
            filename=os.path.join(
                "scripts", "Profile_Default_Action_CustomAction1_Task_Task1.py"
            ),
            target=ref(Service1),
        )


class SimpleBlueprintWithGlobalVariable(Blueprint):

    services = [Service1]
    packages = [Package1]
    substrates = [VM1]
    profiles = [Default]
    credentials = [BP_CRED_cred]
    global_variables = [Ref.GlobalVariable("gv_var")]


class BpMetadata(Metadata):

    categories = {"TemplateType": "Vm"}
    project = Ref.Project("default")
