# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from calm.dsl.builtins import CalmTask as CalmVarTask
from calm.dsl.builtins import *  # no_qa
from calm.dsl.runbooks import CalmEndpoint as Endpoint

DSL_CONFIG = json.loads(read_local_file(".tests/config.json"))
GCP_ACCOUNT = DSL_CONFIG["ACCOUNTS"]["GCP"][1]

# Secret Variables

BP_CRED_efnwk_PASSWORD = read_local_file(".tests/password")

# Credentials
BP_CRED_efnwk = basic_cred(
    "enwfokwe",
    BP_CRED_efnwk_PASSWORD,
    name="efnwk",
    type="PASSWORD",
    default=True,
)


class Service1(Service):

    pass


class VM1(Substrate):

    os_type = "Linux"
    provider_type = "GCP_VM"
    provider_spec = read_provider_spec(os.path.join("specs", "VM1_provider_spec.yaml"))
    provider_spec.spec.get("resources", {})["account_uuid"] = GCP_ACCOUNT.get("UUID")
    provider_spec_editables = read_spec(
        os.path.join("specs", "VM1_create_spec_editables.yaml")
    )
    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=True,
        retries="5",
        connection_port=22,
        address="@@{public_ip_address}@@",
        delay_secs="60",
        credential=ref(BP_CRED_efnwk),
    )


class Package1(Package):

    services = [ref(Service1)]


class deployment_db203d7a(Deployment):

    min_replicas = "1"
    max_replicas = "1"
    default_replicas = "1"

    packages = [ref(Package1)]
    substrate = ref(VM1)


class Default(Profile):

    environments = [Ref.Environment(name="test_env1364451608d5")]
    deployments = [deployment_db203d7a]


class gcp_bp_mvm(Blueprint):

    services = [Service1]
    packages = [Package1]
    substrates = [VM1]
    profiles = [Default]
    credentials = [BP_CRED_efnwk]


class BpMetadata(Metadata):

    project = Ref.Project("default")
