# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated environment DSL (.py)
"""

from calm.dsl.builtins import *

# Secret Variables
BP_CRED_test_creds_PASSWORD = read_local_file("BP_CRED_test_creds_PASSWORD")
BP_CRED_test_creds = basic_cred(
    "admin",
    BP_CRED_test_creds_PASSWORD,
    name="test_creds",
    type="PASSWORD",
)


class Untitled(Substrate):

    os_type = "Linux"
    provider_type = "VMWARE_VM"
    provider_spec = read_vmw_spec(os.path.join("specs", "Untitled_provider_spec.yaml"))
    provider_spec_editables = read_spec(
        os.path.join("specs", "Untitled_create_spec_editables.yaml")
    )
    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=True,
        retries="5",
        connection_port=22,
        address="@@{platform.ipAddressList[0]}@@",
        delay_secs="60",
    )


class ENV_test_decompile_env_vmware(Environment):
    substrates = [Untitled]
    credentials = [BP_CRED_test_creds]

    providers = [
        Provider.Vmware(
            account=Ref.Account("vmware_second"),
        ),
    ]
