# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated environment DSL (.py)
"""

from calm.dsl.builtins import *

# Secret Variables
BP_CRED_test_creds_PASSWORD = read_local_file("BP_CRED_test_creds_PASSWORD")
BP_CRED_test_creds = basic_cred(
    "admin",
    BP_CRED_test_creds_PASSWORD,
    name="test_creds",
    type="PASSWORD",
)


class Untitled(Substrate):

    os_type = "Windows"
    provider_type = "AWS_VM"
    provider_spec = read_provider_spec(
        os.path.join("specs", "Untitled_provider_spec.yaml")
    )

    readiness_probe = readiness_probe(
        connection_type="POWERSHELL",
        disabled=False,
        retries="5",
        connection_port=5985,
        address="@@{public_ip_address}@@",
        delay_secs="60",
    )


class Untitled_1(Substrate):

    name = "Untitled"

    os_type = "Linux"
    provider_type = "AWS_VM"
    provider_spec = read_provider_spec(
        os.path.join("specs", "Untitled_1_provider_spec.yaml")
    )

    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=True,
        retries="5",
        connection_port=22,
        address="@@{public_ip_address}@@",
        delay_secs="60",
    )


class ENV_test_decompile_env_aws(Environment):
    substrates = [Untitled, Untitled_1]
    credentials = [BP_CRED_test_creds]

    providers = [
        Provider.Aws(
            account=Ref.Account("primary"),
        ),
    ]
