# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata

# Endpoints
exec_name = Endpoint.use_existing("exec_name")


# Runbook
@runbook
def runbook_with_execution_name(execution_name="@@{calm_runbook_name}@@_@@{calm_hour}@@_v@@{calm_random}@@"):

    CalmTask.Exec.escript.py3(
        name="Task 1",
        filename=os.path.join("scripts", "_Runbook_with_execution_name_Task_Task1.py"),
        target=ref(exec_name),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("exec_name")
