# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata


# Runbook
@runbook
def RunbookWithGlobalVariable():

    rb_var = CalmVariable.Simple(
        "123",
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=False,
        description="",
    )  # noqa
    global_variables = [Ref.GlobalVariable("gv_var")]

    CalmTask.Exec.escript.py3(
        name="Task 1",
        filename=os.path.join(
            "scripts", "_Runbook_RunbookWithGlobalVariable_Task_Task1.py"
        ),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("default")
