# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from tests.utils import get_approval_project
from calm.dsl.builtins import *  # no_qa

DSL_CONFIG = json.loads(read_local_file(".tests/config.json"))
POLICY_PROJECT = get_approval_project(DSL_CONFIG)
POLICY_PROJECT_CONFIG = DSL_CONFIG["POLICY_PROJECTS"]["PROJECT1"]
VMWARE_ACCOUNT = POLICY_PROJECT_CONFIG["ACCOUNTS"]["VMWARE"][0]

# Secret Variables
BP_CRED_root_PASSWORD = read_local_file(".tests/password")

# Credentials
BP_CRED_root = basic_cred(
    "root",
    BP_CRED_root_PASSWORD,
    name="root",
    type="PASSWORD",
    default=True,
)


class Service1(Service):

    pass


class VM1(Substrate):

    os_type = "Linux"
    provider_type = "VMWARE_VM"
    provider_spec = read_vmw_spec(os.path.join("specs", "VM1_provider_spec.yaml"))
    provider_spec.spec.get("resources", {})["account_uuid"] = VMWARE_ACCOUNT.get("UUID")
    provider_spec_editables = read_spec(
        os.path.join("specs", "VM1_create_spec_editables.yaml")
    )
    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=False,
        retries="5",
        connection_port=22,
        address="@@{platform.ipAddressList[0]}@@",
        delay_secs="120",
        credential=ref(BP_CRED_root),
    )


class Package1(Package):

    services = [ref(Service1)]


class VmwareDeployment(Deployment):

    name = "480522e0_deployment"
    min_replicas = "1"
    max_replicas = "1"
    default_replicas = "1"

    packages = [ref(Package1)]
    substrate = ref(VM1)


class Default(Profile):

    deployments = [VmwareDeployment]


class test_vmware_bp(Blueprint):

    services = [Service1]
    packages = [Package1]
    substrates = [VM1]
    profiles = [Default]
    credentials = [BP_CRED_root]


class BlueprintMetadata(Metadata):
    project = Ref.Project(POLICY_PROJECT)
