# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)

# Endpoints
Endpoint_12072659 = Endpoint.use_existing("Endpoint_12072659")


# Runbook
@runbook
def test_generic_rb():

    CalmTask.Exec.ssh(
        name="Task 1",
        filename=os.path.join("scripts", "_Runbook_test_generic_rb_Task_Task1.sh"),
        target=ref(Endpoint_12072659),
    )


def main():
    print(runbook_json(test_generic_rb))


if __name__ == "__main__":
    main()
