name: Setup & build calm-dsl
on:
  push:
    branches:
      - 'test_image/**'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: black
      uses: psf/black@stable # Exclude list is not honored - https://github.com/psf/black/issues/1584
      with:
        version: "22.6.0"
        options: "--check --extend-exclude tests/escript/scripts/"
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Install requirements
      run: |
        make dev
    - name: Build python package
      run: |
        make dist
    - name: Build docker image
      run: |
        make docker
    - name: Execute container
      uses: addnab/docker-run-action@v3
      with:
        image: ntnx/calm-dsl
        run: calm
    - name: Publish docker image to jfrog-artifactory
      if: ${{ github.event_name == 'push' && github.repository == 'nutanix/calm-dsl' && matrix.python-version == '3.7'}}
      run: |
        docker login ${{ secrets.JFROG_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }}
        docker tag ntnx/calm-dsl:latest ${{ secrets.JFROG_REGISTRY }}/calm-dsl/ntnx_calm_dsl:unsigned_101
        docker push ${{ secrets.JFROG_REGISTRY }}/calm-dsl/ntnx_calm_dsl:unsigned_101
