name: Update release containers
on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: black
      uses: psf/black@stable
      with:
        version: "22.6.0"
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Build docker image
      run: |
        make release-docker
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat CalmVersion)"
    - name: Execute container
      uses: addnab/docker-run-action@v3
      with:
        image: ntnx/calm-dsl:v${{ steps.getversion.outputs.version }}
        run: calm
    - name: Publish docker image
      if: ${{ github.event_name == 'push' && github.repository == 'nutanix/calm-dsl'}}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ntnx/calm-dsl:v${{ steps.getversion.outputs.version }}
